server:
  port: 7777
  shutdown: immediate

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:order_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitTemplate: debug
    org.springframework.amqp.rabbit.connection: debug
    com.rabbitmq.client: debug
    org.springframework:
      cache: trace
      amqp.rabbit.core: info
